### ISSUE TITLE
Website does not have the correct trademark disclaimer

### ISSUE THREAD

**Issue by thisisobate** [project-akri/akri-docs#107]
As part of our ongoing effort to https://github.com/cncf/techdocs/issues/198, we noticed that the website does not pass the trademark criteria on [CLOMonitor](https://clomonitor.io/search?foundation=cncf&not_passing_check=trademark_disclaimer&page=1).

To fix this:
Head to the source code of the website. In the `<footer>` section, add a **disclaimer** or **link** to the Linux foundation trademark disclaimer page:

**Disclaimer**
```
<footer>
   <p>The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, 
         please see our <a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademark Usage page</a>.
   </p>
</footer>
```

**Link**
```
 <footer>
      <ul>
          <li><a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademarks</a></li>
      </ul>
 </footer>
```

**Comment by kate-goldenring** [comment]
@thisisobate the GitBook free version we use does not support footers. Would CNCF support us in upgrading to pro or enterprise? Or is there a different documents CMS that we should move to?

**Comment by thisisobate** [comment]
We usually advise all our projects to use the `Hugo/docsy/netlify` stack. In case you're looking to migrating on the long term, please feel free to open a ticket on our [servicedesk](https://cncfservicedesk.atlassian.net/) platform.

For a quick fix, you can actually add the disclaimer at the bottom of your readme page:
```
<p>The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, 
         please see our <a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademark Usage page</a>.
   </p>
```
That should do the trick @kate-goldenring
