### ISSUE TITLE
Create an adopters file

### ISSUE THREAD

**Issue by kate-goldenring** [project-akri/akri-docs#110]
We should have a list of all the projects/products currently using Akri and a way of adding yourself

**Comment by yujinkim-msft** [comment]
link to current adopters.md file in the main repo -- make sure we don't have two different files and point to existing one

**Comment by yujinkim-msft** [comment]
@EthanChangAED

**Comment by EthanChangAED** [comment]
@kate-goldenring, @yujinkim-msft, would like to check if the following high-level approach is what we want before I proceed.
- Minor modification for the adopters.md in project-akri/akri so the content also is ready for home site.
- Add a [Github File Sync Action](https://github.com/marketplace/actions/repo-file-sync-action) to the workflow so it auto-sync the file to akri-docs/docs/community.
- For adding yourself, user will be direct to project-akri/akri for filing PR.

**Comment by kate-goldenring** [comment]
@EthanChangAED rather than creating an empty page on the site, for starters, i would add a section to the landing page or contributing page that says something along the lines of "are you an adopter? please add yourself here [ref out to adopters.md]"
