### ISSUE TITLE
links in the rendered HTML have very low contrast with regular text

### ISSUE THREAD

**Issue by terceiro** [project-akri/akri-docs#25]
When reading the documentation, it' s pretty difficult to spot what parts of the text are links as links are not displayed much differently from regular text. For example see the screenshot below:

![Screen Shot 2022-03-10 at 11 33 56](https://user-images.githubusercontent.com/30027/157684011-4b94c931-72e8-40af-8ea8-5dd96f9c6bfa.png)

At least for me it' s a bit difficult to spot that the instances of "here" are links.

**Comment by kate-goldenring** [comment]
@terceiro good point. The contrast is very poor. @edrickwong do we need to change the GitBooks color scheme for this?

**Comment by edrickwong** [comment]
I'm currently taking a look into this. When I first started the website, GitBook didn't have any way to change link colors, which I think is still the case. I'll file a support ticket with them to see if there's any way to change this.

**Comment by terceiro** [comment]
yes it's much better now
