### ISSUE TITLE
Community -> Contributing -> CLA section is outdated

### ISSUE THREAD

**Issue by diconico07** [project-akri/akri-docs#82]
The CLA section should be replaced by DCO description

**Comment by ATREAY** [comment]
Hey @kate-goldenring,

Since I'm just getting started with open source, can I take this issue?

**Comment by diconico07** [comment]
Hi @ATREAY,

Sure, I assign the issue to you.

**Comment by ATREAY** [comment]
Hello @diconico07, 

I have made the necessary modifications, and I kindly request you to review them.

Thank you!
